name: mapsforge_flutter
description: A port of mapsforge for pure flutter
version: 1.1.0
# author: devemux86, mikes222
homepage: https://github.com/mikes222/mapsforge_flutter

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BSD License
  logging: ^0.11.4

  # BSD License
  convert: ^2.1.1

  # MIT License
  ecache: ^1.0.1
#    git:
#      url: https://github.com/mikes222/dcache
    #path: ../../github_dcache/

  # MIT License
  # xml: ^4.5.1
  xml: '>=4.5.1 <=5.0.2'

  # Apache 2.0 License
  rxdart: ^0.25.0

  # BSD License
  synchronized: ^2.2.0+2

  # BSD License
  # flutter_svg: ^0.19.1
  flutter_svg: ^0.21.0-nullsafety.0

  # BSD License
  #image: 2.1.13

  # BSD License
  path_provider: ^1.6.27

  # MIT License
  provider: ^4.3.2+3

  # BSD License
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

#  assets:
#    - assets/defaultrender.xml
#    - assets/simplerender.xml
